### ISSUE TITLE
FileExistsError on start of the program

### ISSUE THREAD

**Issue by eku** [NinjaCheetah/NUSGet#11]
### Describe the bug

The execcutable inside the tar archive has the same name as the directory it tries to create, resulting in a fail.

Also the call of “NUSget -h” to get help for CLI option fails for the same reason. The help function should not want to create a directory first.

### Steps to Reproduce

$ ./NUSget

### Screenshot(s) (if applicable)

$ ./NUSGet 
FileExistsError: [Errno 17] File exists: '/home/user/Downloads/NUSGet'

### System information:
 - **OS and version:** Fedora 40
 - **NUSGet version:** 1.2.0

**Comment by NinjaCheetah** [comment]
Hmm, it hadn't occurred to me that running the binary from your downloads folder would cause issues, because of the colliding executable/output directory name. I plan to add more customization to where titles are downloaded to in the future, but as a temporary fix for right now, you can move the NUSGet executable anywhere else or rename it. Personally my recommendation for Linux users right now is to build the program yourself, because then you can also `sudo make install` it and have it appear in your application launcher, and that also entirely negates this issue.

As for CLI usage, NUSGet does not have a CLI at all, as it is only designed to be a GUI app. If you're looking for a CLI to download from the NUS, you'll want to check out my other program [WiiPy](https://github.com/NinjaCheetah/WiiPy) instead.

**Comment by eku** [comment]
In other words, a desktop program that creates a directory in the current working directory before the UI is opened. Without the user having any influence on it.

You suggest compiling and installing it myself. Have you considered a Python module that can be installed via pip/poetry in a virtual env?

**Comment by NinjaCheetah** [comment]
The latest commit changed the download target from "NUSGet" to "NUSGet Downloads". This isn't a perfect solution, but it resolves this issue for the time being while I work out a cross-platform solution for storing settings, which will allow for custom download locations.

Closing this issue now.
