### ISSUE TITLE
NUSGet.app on macOS Sequoia 15.0 Shows ‘Damaged and Can’t Be Opened’ Error on Launch

### ISSUE THREAD

**Issue by archpc** [NinjaCheetah/NUSGet#5]
### **Describe the bug**

I downloaded the latest release for macOS (1.1.0) from the GitHub releases page and extracted the tar.gz file with Keka. The application inside appears to be intact, but when I open NUSGet.app, the icon bounces on the dock, and I receive an error message in Finder stating: "NUSGet" is damaged and can't be opened. You should move it to the Trash.

### **To Reproduce**

1. Download the NUSGet 1.1.0 release for macOS from the GitHub releases page.
2. Extract the tar.gz file using Keka.
3. Attempt to open NUSGet.app.

### **Screenshots (optional)**

<img width="783" alt="Screenshot 2024-08-20 at 4 47 41 PM" src="https://github.com/user-attachments/assets/cb1b873f-280d-4b76-b7ea-4bc1bdc65955">

### **Computer (please complete the following information):**
- **OS:** macOS Sequoia 15.0
- **NUSGet version:** 1.1.0
- **Python version:** 3.12.5
- **Hardware:** Late 2023 14-inch MacBook Pro, M3 Pro, 36GB RAM, arm64 CPU
- **Software:** Rosetta 2 installed, Wine Stable installed from Homebrew

**Comment by NinjaCheetah** [comment]
Thanks for the report!

I believe this is because I'm using a relative path to access files during NUSGet's startup. For whatever reason, if an app tries to use a relative path, macOS deems it "damaged" and tells you to delete it. As a workaround, you can launch the actual executable at `NUSGet.app/Contents/MacOS/NUSGet` and it should work as expected.

You can also try the latest nightly build from [here](https://github.com/NinjaCheetah/NUSGet/actions/runs/10437547043), which may have this fixed already. Let me know if that build works normally, and if not then I'll pull my old Mac out and see if I can get it working.

**Comment by NinjaCheetah** [comment]
Ahh okay, good old Gatekeeper. I'll add a note about removing the quarantine flag, especially since I know that macOS Sequoia and later are going to require using `xattr`, unlike Sonoma and earlier that would let you right-click -> open to un-quarantine it.

Glad to know that it's working properly beyond that though! I'll let you know if there's any other macOS-specific stuff to test in the future.
